### ISSUE TITLE
Can you specified a way to generate master secret key?

### ISSUE THREAD

**Issue by pangzi-debug** [PhilippSchindler/ethdkg#4]

**Comment by PhilippSchindler** [comment]
Sorry for the late reply. This is specified in section 5.3. Key Derivation in the research paper (see [https://github.com/PhilippSchindler/ethdkg/blob/master/paper/ethdkg.pdf](https://github.com/PhilippSchindler/ethdkg/blob/master/paper/ethdkg.pdf)). But typically you want to use the key shares and, for example, only aggregate signatures shares rather then deriving the master secret key.
